"""Renamed image_name to image in Recipe

Revision ID: 04165eea4286
Revises: 8e7e74c31e74
Create Date: 2024-03-31 21:32:53.522956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04165eea4286'
down_revision = '8e7e74c31e74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###
