"""Changed the way db is stuctured

Revision ID: 16f288696c73
Revises: 4910ffe36982
Create Date: 2024-03-31 21:03:57.983043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16f288696c73'
down_revision = '4910ffe36982'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('time_in_minutes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('measurement', sa.String(length=100), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instruction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('step', sa.Text(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('quantities')
    op.drop_table('recipes')
    op.drop_table('ingredients')
    op.drop_table('recipe_ingredients')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_ingredients',
    sa.Column('recipe_id', sa.INTEGER(), nullable=False),
    sa.Column('ingredient_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity_id', sa.INTEGER(), nullable=True),
    sa.Column('amount', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.ingredient_id'], ),
    sa.ForeignKeyConstraint(['quantity_id'], ['quantities.quantity_id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.recipe_id'], ),
    sa.PrimaryKeyConstraint('recipe_id', 'ingredient_id')
    )
    op.create_table('ingredients',
    sa.Column('ingredient_id', sa.INTEGER(), nullable=False),
    sa.Column('ingredient_name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('ingredient_id')
    )
    op.create_table('recipes',
    sa.Column('recipe_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('time_in_minutes', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('recipe_id')
    )
    op.create_table('quantities',
    sa.Column('quantity_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity_name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('quantity_id')
    )
    op.drop_table('instruction')
    op.drop_table('ingredient')
    op.drop_table('recipe')
    # ### end Alembic commands ###
