"""Changed time_in_minutes to time in Recipe table

Revision ID: 25e86a946bd2
Revises: 16f288696c73
Create Date: 2024-03-31 21:05:46.918999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25e86a946bd2'
down_revision = '16f288696c73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.Integer(), nullable=True))
        batch_op.drop_column('time_in_minutes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_in_minutes', sa.INTEGER(), nullable=True))
        batch_op.drop_column('time')

    # ### end Alembic commands ###
